version: "3"
services:
  pg:
    image: postgres:9.4

  audit:
    image: postgres:9.4

  testdb:
    image: postgres:9.3
    environment:
      POSTGRES_PASSWORD: postgres_secret

  conjur:
    build:
      context: ../
      dockerfile: dev/Dockerfile.dev
    image: conjur-dev
    environment:
      CONJUR_APPLIANCE_URL: http://localhost:3000
      DATABASE_URL: postgres://postgres@pg/postgres
      CONJUR_ADMIN_PASSWORD: admin
      CONJUR_ACCOUNT: cucumber
      CONJUR_PASSWORD_ALICE: secret
      CONJUR_DATA_KEY:
      RAILS_ENV:
      CONJUR_LOG_LEVEL: debug
    ports:
      - "3000:3000"
      - "1234:1234"
    expose:
      - "3000"
    volumes:
    - ..:/src/conjur-server
    - ../../conjur-policy-parser:/src/conjur-policy-parser
    - authn-local:/run/authn-local
    - ../ci/ldap-certs:/ldap-certs:ro
    links:
    - pg:pg
    - ldap-server
    - oidc-keycloak:keycloak

  cucumber:
    image: conjur-dev
    entrypoint: sleep
    command: infinity
    environment:
      LDAP_URI: ldap://ldap-server:389
      LDAP_BASE: dc=conjur,dc=net
      CONJUR_APPLIANCE_URL: http://conjur:3000
      DATABASE_URL: postgres://postgres@pg/postgres
      CONJUR_ADMIN_PASSWORD: admin
      CONJUR_DATA_KEY:
      RAILS_ENV:
    volumes:
      - ..:/src/conjur-server
      - authn-local:/run/authn-local
      - ../ci/ldap-certs:/ldap-certs:ro
    links:
      - conjur
      - pg
      - testdb

  client:
    image: cyberark/conjur-cli:5
    entrypoint: sleep
    command: infinity
    environment:
      CONJUR_APPLIANCE_URL: http://conjur:3000
      CONJUR_ACCOUNT: cucumber
      CONJUR_AUTHN_LOGIN: admin
    links:
    - conjur:conjur
    volumes:
    - ..:/src/conjur-server

  ldap-server:
    image: osixia/openldap
    command: --copy-service --loglevel debug
    hostname: ldap-server
    environment:
      LDAP_ORGANISATION: CyberArk
      LDAP_DOMAIN: conjur.net
      LDAP_ADMIN_PASSWORD: ldapsecret
      LDAP_TLS_CA_CRT_FILENAME: "ca-chain.cert.pem"
      LDAP_TLS_CRT_FILENAME: "ldap-server.cert.pem"
      LDAP_TLS_KEY_FILENAME: "ldap-server.key.pem"
      LDAP_TLS_VERIFY_CLIENT: try

    volumes:
      - ./files/authn-ldap/ldap:/container/service/slapd/assets/config/bootstrap/ldif/custom
      - ../ci/ldap-certs:/container/service/slapd/assets/certs:ro

  oidc-keycloak:
    image: jboss/keycloak:4.3.0.Final
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_APP_USER=alice
      - KEYCLOAK_APP_USER_PASSWORD=alice
      - KEYCLOAK_APP_USER_EMAIL=alice@conjur.net
      - KEYCLOAK_SECOND_APP_USER=bob
      - KEYCLOAK_SECOND_APP_USER_PASSWORD=bob
      - KEYCLOAK_SECOND_APP_USER_EMAIL=bob@conjur.net
      - KEYCLOAK_NON_CONJUR_APP_USER=not_in_conjur
      - KEYCLOAK_NON_CONJUR_APP_USER_PASSWORD=not_in_conjur
      - KEYCLOAK_NON_CONJUR_APP_USER_EMAIL=not_in_conjur
      - DB_VENDOR=H2
      - KEYCLOAK_CLIENT_ID=conjurClient
      - KEYCLOAK_REDIRECT_URI=http://locallhost.com/
      - KEYCLOAK_CLIENT_SECRET=1234
      - KEYCLOAK_SCOPE=openid
    ports:
      - "7777:8080"
    volumes:
      - ../ci/authn-oidc/keycloak/standalone.xml:/opt/jboss/keycloak/standalone/configuration/standalone.xml
      - ../ci/authn-oidc/keycloak:/authn-oidc/keycloak/scripts

  okta-ldap-agent:
    image: weareenvoy/okta-ldap-agent
    volumes:
      - ./files/okta-ldap-agent/conf:/opt/Okta/OktaLDAPAgent/conf
    entrypoint: sleep
    command: infinity

volumes:
  authn-local:
