version: "3"
services:
  pg:
    image: postgres:9.4

  testdb:
    image: postgres:9.3

  conjur:
    image: "conjur:${TAG}"
    environment:
      DATABASE_URL: postgres://postgres@pg/postgres
      CONJUR_ADMIN_PASSWORD: admin
      CONJUR_ACCOUNT: cucumber
      CONJUR_DATA_KEY:
      RAILS_ENV:
      CONJUR_LOG_LEVEL: debug
      CONJUR_AUTHENTICATORS: authn-ldap/test,authn-ldap/secure,authn-oidc/keycloak
      LDAP_URI: ldap://ldap-server:389
      LDAP_BASE: dc=conjur,dc=net
      LDAP_FILTER: '(uid=%s)'
      LDAP_BINDDN: cn=admin,dc=conjur,dc=net
      LDAP_BINDPW: ldapsecret
    command: server
    volumes:
      - authn-local:/run/authn-local
      - ./authn-oidc/keycloak:/authn-oidc/keycloak/scripts
      - ./ldap-certs:/ldap-certs:ro
      - log-volume:/opt/conjur-server/log
    expose:
      - "80"
    links:
      - pg
      - ldap-server
      - oidc-keycloak:keycloak

  cucumber:
    image: conjur-test:$TAG
    entrypoint: bash
    working_dir: /src/conjur-server
    environment:
      CONJUR_APPLIANCE_URL: http://conjur
      CONJUR_ACCOUNT: cucumber
      DATABASE_URL: postgres://postgres@pg/postgres
      RAILS_ENV: test
      CONJUR_LOG_LEVEL: debug
      CONJUR_DATA_KEY:
      REPORT_ROOT:
      CUCUMBER_NETWORK:
    volumes:
      - ..:/src/conjur-server
      - authn-local:/run/authn-local
      - ./ldap-certs:/ldap-certs:ro
      - log-volume:/src/conjur-server/log
    links:
      - conjur
      - pg
      - testdb
      - oidc-keycloak:keycloak

  ldap-server:
    image: osixia/openldap
    command: --copy-service --loglevel debug
    hostname: ldap-server
    environment:
      LDAP_ORGANISATION: CyberArk
      LDAP_DOMAIN: conjur.net
      LDAP_ADMIN_PASSWORD: ldapsecret
      LDAP_TLS_DH_PARAM_FILENAME: "dhparam.pem"
      LDAP_TLS_CA_CRT_FILENAME: "ca-chain.cert.pem"
      LDAP_TLS_CRT_FILENAME: "ldap-server.cert.pem"
      LDAP_TLS_KEY_FILENAME: "ldap-server.key.pem"
      LDAP_TLS_VERIFY_CLIENT: try
    volumes:
      - ./authn-ldap/ldap-data:/container/service/slapd/assets/config/bootstrap/ldif/custom
      - ./ldap-certs:/container/service/slapd/assets/certs:ro

  oidc-keycloak:
    image: jboss/keycloak:4.3.0.Final
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_APP_USER=alice
      - KEYCLOAK_APP_USER_PASSWORD=alice
      - KEYCLOAK_APP_USER_EMAIL=alice@conjur.net
      - KEYCLOAK_SECOND_APP_USER=bob
      - KEYCLOAK_SECOND_APP_USER_PASSWORD=bob
      - KEYCLOAK_SECOND_APP_USER_EMAIL=bob@conjur.net
      - KEYCLOAK_NON_CONJUR_APP_USER=not_in_conjur
      - KEYCLOAK_NON_CONJUR_APP_USER_PASSWORD=not_in_conjur
      - KEYCLOAK_NON_CONJUR_APP_USER_EMAIL=not_in_conjur
      - DB_VENDOR=H2
      - KEYCLOAK_CLIENT_ID=conjurClient
      - KEYCLOAK_REDIRECT_URI=http://locallhost.com/
      - KEYCLOAK_CLIENT_SECRET=d7047915-9029-45b8-9bd6-7ec5c2f75e5b
      - KEYCLOAK_SCOPE=openid
    ports:
      - "7777:8080"
    volumes:
      - ./authn-oidc/keycloak:/scripts
      - ./authn-oidc/keycloak/standalone.xml:/opt/jboss/keycloak/standalone/configuration/standalone.xml


volumes:
  authn-local:
  log-volume:
